version: '3'

services:
  ch_server:
    container_name: clickhouse-server
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
    volumes:
      - ./db:/var/lib/clickhouse
      
  ch_client:
    container_name: clickhouse-client
    image: yandex/clickhouse-client
    entrypoint:
      - /bin/sleep
    command:
      - infinity